---
driver:
  name: vagrant

provisioner:
  name: chef_zero
 # require_chef_omnibus: 11.16.4

platforms:
  - name: ubuntu-14.04

suites:
  - name: webserver
    driver:
      vm_hostname: www
      network:
        - ["forwarded_port", {guest: 80, host: 8080}]
      customize:
        memory: 2048
        cpus: 2
    run_list:       
       - recipe[apt]
       - recipe[apache2::default]
       - recipe[java::oracle]
       - recipe[php]
       - recipe[imagemagick]
       - recipe[webserver::default]
    attributes:
       webserver:
         name: www
         version: "0.0.1"

         
