---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4

platforms:
  - name: ubuntu-14.04

suites:
  - name: webserver
    run_list:
       - recipe[java::oracle]
       - recipe[apt]
       - recipe[mysqld]
       - recipe[webserver::default]
    attributes:
       webserver:
         name: www
         version: "0.0.1"
