---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4

platforms:
  - name: ubuntu-14.04

suites:
  - name: webserver
    run_list:       
       - recipe[apt]
       - recipe[java::oracle]
       - recipe[php]
       - recipe[mysqld]
       - recipe[webserver::mediawiki]
       - recipe[webserver::config_mysql]
       - recipe[webserver::default]
    attributes:
       webserver:
         name: www
         version: "0.0.1"
         network:
           - ["private_network", { ip: "192.168.0.236" }]

           
